### ISSUE TITLE
heavy noise on voice from audio jack on mic array v2

### ISSUE THREAD

**Issue by mars-japan** [respeaker/usb_4_mic_array#25]
We play voice messages through a powered speaker connected to audio jack on ReSpeaker mic array v2.
When playing sound (any source) the output (audio jack of the mic array v2) is corrupted with an horrible loud noise.

Any idea or suggestion of how to identify the problem and correct it please ?

**Comment by sradmard** [comment]
Hi, I am experiencing the same thing sometimes on my mic array v2. Is there any update on this?

**Comment by MexXxo** [comment]
I experienced the same. My Setup was Raspbian Jessie, Pulseaudio (I think it was 9, the version that is delivered with jessie) and the 48 Khz Firmware from the Issue Ticket.

I have updated to raspbian stretch and pulseaudio 12.2 and testing it again, will see if it also happens there...

**Comment by MexXxo** [comment]
Also happens on stretch with pulseaudio 12.2

**Comment by Kuldeepwadaskar** [comment]
same with us
looking for some solution. voice get recorded but heavy noise

**Comment by Kuldeepwadaskar** [comment]
@MexXxo  did you got any solution?
please let me know

**Comment by MexXxo** [comment]
Dropped the respeaker, due to lacking firmware... Only thing I noticed is that with the 16 kHz firmware it went better (did not occurred but I did not do any heavy tests), so if you can live with 16 kHz (I can not), this is the way to go.

**Comment by Kuldeepwadaskar** [comment]
first time when we tested, it worked better, but don't know what happened in 2nd turn.
any other solution regarding this @mars-japan , @xiongyihui

**Comment by jerryyip** [comment]
@Kuldeepwadaskar Please try the latest firmware, we have fixed this problem already.

**Comment by saikishor** [comment]
@jerryyip We are still facing the same issue with our respeaker. We have installed the recent firmware available on the repo, but still the issue persists. Could you please comment on this?.

**Comment by saikishor** [comment]
@jerryyip Please find the audio file for your reference.
https://drive.google.com/drive/folders/1jWOO6c-uKaKN0tq5nyIEqoLAI9H7IyX5?usp=sharing

**Comment by v-lopez** [comment]
To add to what @saikishor said, it does not always behave like this. We experienced twice over a month ago with the 48k_1_channel_firmware.bin and today with the 48k_6_channels_firmware.bin.

We have checked the md5sum of the firmware and it is the same as the last version published here on github master branch.

**Comment by v-lopez** [comment]
Still happening with the 16k 6 channel latest firmware as well.

As you can see in the file linked by @saikishor, we play an audio through the respeaker to the speakers. We recorded all 6 channels and you can see that the played audio is gibberish.

If we connect the speakers to another media device (such as a phone) the audio is played fine.
